Improved readability of tests
slackapi/java-slack-sdk pull request #1025
Opened 2022-07-15 15:30 UTC by WilliamBergamin

Improved the readability of newly created test to:

-  facilitate the understanding of http status codes in tests
- ensure that content types and other web standards are maintained

I don't know if we want to implement this for every test in the library, maybe someone can comment on this?

### Category (place an `x` in each of the `[ ]`)

* [x] **bolt** (Bolt for Java)
* [x] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

2022-07-15 20:23 UTC, seratch requested changes
Thanks for the changes. Can you make the constants static?

2022-07-15 20:23 UTC, seratch commented on bolt-jakarta-servlet/src/test/java/test_locally/servlet_test/InvalidRequestPatternTest.java
> +    private final String CONTENT_TYPE = HttpHeader.CONTENT_TYPE.toString();
If you use all capital letters for these, you can make them static.
```suggestion
    private static final String TEXT_PLAIN = MimeTypes.Type.TEXT_PLAIN.getContentTypeField().getValue();
    private static final String APPLICATION_JSON = MimeTypes.Type.APPLICATION_JSON.getContentTypeField().getValue();
    private static final String CONTENT_TYPE = HttpHeader.CONTENT_TYPE.toString();
```

2022-07-15 20:23 UTC, seratch commented on bolt-jakarta-servlet/src/test/java/test_locally/servlet_test/SlashCommandTest.java
> +    private final String CONTENT_TYPE = HttpHeader.CONTENT_TYPE.toString();
```suggestion
    private static final String TEXT_PLAIN = MimeTypes.Type.TEXT_PLAIN.getContentTypeField().getValue();
    private static final String APPLICATION_JSON = MimeTypes.Type.APPLICATION_JSON.getContentTypeField().getValue();
    private static final String CONTENT_TYPE = HttpHeader.CONTENT_TYPE.toString();
```

2022-07-15 20:23 UTC, seratch commented on bolt-servlet/src/test/java/test_locally/servlet_test/InvalidRequestPatternTest.java
> +    private final String CONTENT_TYPE = HttpHeader.CONTENT_TYPE.toString();
```suggestion
    private static final String TEXT_PLAIN = MimeTypes.Type.TEXT_PLAIN.getContentTypeField().getValue();
    private static final String APPLICATION_JSON = MimeTypes.Type.APPLICATION_JSON.getContentTypeField().getValue();
    private static final String CONTENT_TYPE = HttpHeader.CONTENT_TYPE.toString();
```

2022-07-15 20:23 UTC, seratch commented on bolt-servlet/src/test/java/test_locally/servlet_test/SlashCommandTest.java
> +    private final String CONTENT_TYPE = HttpHeader.CONTENT_TYPE.toString();
```suggestion
    private static final String TEXT_PLAIN = MimeTypes.Type.TEXT_PLAIN.getContentTypeField().getValue();
    private static final String APPLICATION_JSON = MimeTypes.Type.APPLICATION_JSON.getContentTypeField().getValue();
    private static final String CONTENT_TYPE = HttpHeader.CONTENT_TYPE.toString();
```

2022-07-15 20:23 UTC, seratch commented on bolt/src/test/java/test_locally/app/InvalidPayloadPatternTest.java
> +    private final String CONTENT_TYPE = HttpHeader.CONTENT_TYPE.toString();
```suggestion
    private static final String APPLICATION_JSON = MimeTypes.Type.APPLICATION_JSON.getContentTypeField().getValue();
    private static final String CONTENT_TYPE = HttpHeader.CONTENT_TYPE.toString();
```

2022-07-18 14:50 UTC, filmaj approved these changes

2022-07-19 00:39 UTC, seratch approved these changes

2022-07-19 00:39 UTC, merged