Updating app_requested payload to include new field
slackapi/java-slack-sdk pull request #1355
Opened 2024-08-30 17:46 UTC by gugutagli

Updating ```app_requested``` payload to include ```is_granular_bot_app```

### Category (place an `x` in each of the `[ ]`)

* [x] **bolt** (Bolt for Java)
* [x] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [x] **slack-api-client** (Slack API Clients)
* [x] **slack-api-model** (Slack API Data Models)
* [x] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [x] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

2024-08-30 21:16 UTC, seratch requested changes
This Java class needs to be updated and you can run the unit test that auto-generates the sample JSON file: https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/main/java/com/slack/api/model/admin/AppRequest.java

2024-08-31 01:14 UTC, gugutagli commented
> This Java class needs to be updated and you can run the unit test that auto-generates the sample JSON file: https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-model/src/main/java/com/slack/api/model/admin/AppRequest.java

Thank you, I was able to add to the java file. This is my first time working on this, which test do I run and how do I run them?

2024-08-31 01:27 UTC, seratch requested changes

2024-08-31 01:27 UTC, seratch commented on slack-api-model/src/main/java/com/slack/api/model/admin/App.java
> +    @SerializedName("is_granular_bot_app")
```suggestion
    @SerializedName("is_granular_bot_app")
    private boolean granularBotApp
```

2024-08-31 01:28 UTC, seratch commented
@gugutagli You can run [this script](https://github.com/slackapi/java-slack-sdk/blob/main/scripts/run_no_prep_tests.sh) for it, but it may take time. For this specific pull request, running only [this test](https://github.com/slackapi/java-slack-sdk/blob/main/slack-app-backend/src/test/java/test_locally/sample_json_generation/EventsApiPayloadDumpTest.java) should be fine.

2024-08-31 01:29 UTC, seratch commented on slack-api-model/src/main/java/com/slack/api/model/admin/App.java
> +    @SerializedName("is_granular_bot_app")
If this flag can be absent in some patterns, `private Boolean isGranularBotApp` without SerializedName annotation is suitable.

2024-09-02 03:35 UTC, merged

2024-09-02 03:35 UTC, seratch commented
@gugutagli Thanks for sending this PR!