Fix for Issue #1363
slackapi/java-slack-sdk pull request #1364
Opened 2024-09-09 17:07 UTC by jed204

Fix type for https://github.com/slackapi/java-slack-sdk/issues/1363

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [x] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

2024-09-09 17:49 UTC, WilliamBergamin approved these changes
Thank you for the contribution 🙏 

Please sign [the CLA](https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2Fslackapi%2Fjava-slack-sdk%2Fpull%2F1364)

2024-09-09 17:49 UTC, WilliamBergamin commented on slack-api-model/src/main/java/com/slack/api/model/block/element/RichTextSectionElement.java
> +        private Long timestamp;
Nice catch 💯 I think this may be an `integer` on the backend, but this project uses `Long` for other timestamp values

2024-09-09 17:51 UTC, jed204 commented
> Thank you for the contribution 🙏
> 
> Please sign [the CLA](https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2Fslackapi%2Fjava-slack-sdk%2Fpull%2F1364)

I signed it but there was an error when I submitted - when I try to sign it again it says I signed it already. Any ideas?

2024-09-09 18:03 UTC, WilliamBergamin commented
I see, don't worry about the CLA for now
It seems like some tests are failing, we will need to fix these before merging

2024-09-09 18:03 UTC, WilliamBergamin requested changes
Tests need to pass 🙏

2024-09-10 01:05 UTC, jed204 commented
> Tests need to pass 🙏

Roger. I updated the mock responses. They are passing locally now.

2024-09-10 02:02 UTC, seratch approved these changes
Thank you for sending this PR!

2024-09-10 02:02 UTC, merged